export const CROSSREF_BRANDS: string[] = [
  "Price Industries",
  "Ruskin",
  "Krueger",
  "Titus",
  "Nailor",
  "Tuttle & Bailey",
  "Carnes",
  "MetalAire",
  "POTTORFF",
  "Greenheck",
  "Loren Cook",
  "PennBarry",
  "Twin City Fan",
  "Aerovent",
  "Air Balance",
  "United Enertech",
  "NCA",
  "Arrow",
  "AWV",
  "Cesco",
  "Prefco",
  "Safe-Air",
  "Airolite",
  "Construction Specialties",
  "Dowco",
  "Louvers & Dampers",
  "Vent",
  "Metropolitan Air Technologies",
  "Carrier",
  "Trane",
  "Superior Rex",
  "Rittling",
  "Williams",
  "Daiken",
  "Trox",
  "Swegon",
  "Seiho",
  "Semco",
  "Dadanco",
  "Nuclimate",
  "TWA",
  "Temspec",
  "Tridim",
  "Accutherm",
  "AJ",
  "Air Concepts",
  "Camfil",
  "Young Regulator",
  "Whalen",
  "York",
  "Envirco",
  "Enviro-Tec",
  "First Co",
  "IEC",
  "KEES",
  "MagicAire",
  "McQuay",
  "Acme",
  "Breidert",
  "American Aldes",
  "Solar & Palau",
  "Anemostat"
];
