"""Generate lib/crossref-data.ts from api/_lib/crossref.json.

Run after build-crossref.py updates the JSON. Emits:
  - CROSSREF_BRANDS: string[]
  - CROSSREF_CATEGORIES: string[]
  - BRANDS_BY_CATEGORY: Record<string, string[]>
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
JSON_PATH = os.path.join(ROOT, "api", "_lib", "crossref.json")
OUT = os.path.join(ROOT, "lib", "crossref-data.ts")


def js(s: str) -> str:
    return json.dumps(s, ensure_ascii=False)


def main() -> int:
    with open(JSON_PATH, encoding="utf-8") as f:
        db = json.load(f)

    brands = db["brands"]
    categories = db["categories"]
    bbc = db["brands_by_category"]

    lines = []
    lines.append("// Auto-generated by scripts/emit-crossref-ts.py — do not edit.")
    lines.append("export const CROSSREF_BRANDS: string[] = [")
    for b in brands:
        lines.append(f"  {js(b)},")
    lines.append("];")
    lines.append("")
    lines.append("export const CROSSREF_CATEGORIES: string[] = [")
    for c in categories:
        lines.append(f"  {js(c)},")
    lines.append("];")
    lines.append("")
    lines.append("export const BRANDS_BY_CATEGORY: Record<string, string[]> = {")
    for c in categories:
        arr = bbc.get(c, [])
        inline = ", ".join(js(b) for b in arr)
        lines.append(f"  {js(c)}: [{inline}],")
    lines.append("};")
    lines.append("")

    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"[emit-crossref-ts] wrote {OUT} ({len(brands)} brands, {len(categories)} categories)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
